feat: updated approach for preventing duplicated links
ubiquity/cloudflare-deploy-action pull request #25
Opened 2024-12-21 10:02 UTC by Sadaf-A

Resolves #14

2024-12-21 10:03 UTC, Sadaf-A commented
@0x4007 @rndquu I think the issue persisted because were checking the whole html body which might have some mismatch I updated this approach by checking for duplicated deployment links instead of the whole html body.

2024-12-23 07:16 UTC, rndquu requested changes
Pls add a unit test that checks the issue is no more present

2024-12-23 08:36 UTC, Sadaf-A commented
> Pls add a unit test that checks the issue is no more present

Hey, where are unit test files located?

2024-12-23 09:16 UTC, rndquu commented
> > Pls add a unit test that checks the issue is no more present
> 
> Hey, where are unit test files located?

Add a new one, right now there're no any

2024-12-23 15:13 UTC, Sadaf-A commented
@rndquu Hey, please have a look I have added test cases and they are passing. 

<img width="506" alt="Screenshot 2024-12-23 at 8 42 17 PM" src="https://github.com/user-attachments/assets/01fd2e55-4176-479e-abcd-ac544c8652b8" />

2024-12-23 16:48 UTC, rndquu approved these changes

2024-12-29 06:47 UTC, Sadaf-A commented
@rndquu how long will it take to get merged?

2024-12-29 11:35 UTC, rndquu commented
> @rndquu how long will it take to get merged?

Need 1 more approval

2025-01-01 19:30 UTC, 0x4007 reviewed
Code changes look fine but why don't you post QA

2025-01-01 20:47 UTC, whilefoo requested changes
please post QA

2025-01-01 20:47 UTC, whilefoo commented on utils/check-for-duplicated-links.ts
> +}
this one line function is unnecessary

2025-01-02 02:48 UTC, Sadaf-A commented
@whilefoo I'm not sure how I can do QA for this repo. Could you please provide some steps.

2025-01-03 16:16 UTC, whilefoo commented
> @whilefoo I'm not sure how I can do QA for this repo. Could you please provide some steps.

You can use the Github action on your own repository and test. Just point the action to your own branch `uses: Sadaf-A/cloudflare-deploy-action@prevent-duplicate-links`

2025-01-03 16:25 UTC, Sadaf-A commented
> > @whilefoo I'm not sure how I can do QA for this repo. Could you please provide some steps.
> 
> You can use the Github action on your own repository and test. Just point the action to your own branch `uses: Sadaf-A/cloudflare-deploy-action@prevent-duplicate-links`

Hey, thanks a lot which file should I change?

2025-01-03 16:26 UTC, Sadaf-A commented
> > > @whilefoo I'm not sure how I can do QA for this repo. Could you please provide some steps.
> > 
> > You can use the Github action on your own repository and test. Just point the action to your own branch `uses: Sadaf-A/cloudflare-deploy-action@prevent-duplicate-links`
> 
> Hey, thanks a lot which file should I change?

also could you please help me QA this [PR](https://github.com/ubiquity-os-marketplace/command-ask/pull/46) as well. Thank You

2025-01-04 09:09 UTC, Sadaf-A commented
> > @whilefoo I'm not sure how I can do QA for this repo. Could you please provide some steps.
> 
> You can use the Github action on your own repository and test. Just point the action to your own branch `uses: Sadaf-A/cloudflare-deploy-action@prevent-duplicate-links`

I'm not able to do that could you please elaborate as this is my first time contributing to this repo. 
Thank You

2025-01-04 20:32 UTC, 0x4007 commented
You need to handle your own QA. Ask ChatGPT to guide you, not our core team.

2025-01-21 03:32 UTC, closed without merging